# Generated by Django 4.2.3 on 2023-07-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_vote_value_alter_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
